### ISSUE TITLE
Set activate/checked ?

### ISSUE THREAD

**Issue by Fruchtgummi** [maliMirkec/csstabs#1]
Hi,

How can I activate a tab via the URL?

**Comment by maliMirkec** [comment]
If I understood an issue correctly, this requires handling tab states via JavaScript. Look at this StackOverflow thread: https://stackoverflow.com/questions/1034621/get-the-current-url-with-javascript

**Comment by Fruchtgummi** [comment]
Allright...

```
var anchor = window.location.hash.substr(1);

if (anchor != "") {
    $('*[data-anchor="'+anchor+'"]').prop( "checked", true );
}
jQuery(document).on('click','input[name="msgs_tabs"]',function() {
        window.location.hash = '#'+$(this).data("anchor");
});
```
